package com.akimatBot.entity.enums;

public enum WaitingType {

    START, CHOOSE_BACK, GET_TEG_LIST, DELETE_EMPLOYEE, ADD_EMPLOYEE, DELETE_EMPLOYEE2, ADD_TEG, ADD_TEG_KZ, CHOOSE_DEPARTMENTS, SET_REPORT, CHOICE_OPTION, NEXT_KEYBOARD, COMMAND_EDITOR, SET_TEXT_DESC_BACK, UPDATE_BUTTON, UPDATE_TEXT, UPDATE_BUTTON_LINK, UPDATE_FILE,
    SET_FULL_NAME, SET_PHONE_NUMBER, CHOSE_BUTTON_BUTTON, EDIT_UPDATE_TEXT, EDIT_UPDATE_PHOTO, SET_STRUCTURE_DEPARTMENTS_INFO, EDIT_UPDATE_DEPARTMENTS_TEXT, EDIT_UPDATE_DEPARTMENTS_PHOTO, EDIT_CATEGORY_NAME2,
    SET_QUESTION, WAIT, CHOOSE_RECEPTION, SET_CHOSE, SET_TYPE, SET_TYPE_TYPE, SET_LOCATION, CHOSE_RECEPTION_BUTTON, SET_ADMIN_BY_PHONE, SET_PHOTO_OR_VIDEO, SET_TEG, EDIT_CATEGORY, EDIT_CATEGORY2, OP_CATEGORY,
    SET_IIN, SET_OTHER_PROF_COURSES, SET_OTHER_SOCIAL_NEEDS, EVENT, SET_TEXT, SET_PHOTO, SET_STRUCTURE_INFO, DELETE_ADMIN, ADD_ADMIN, SET_RECEPTION_TYPE, SET_RECEPTION_TEG, EDIT_CATEGORY_NAME, EDIT_TEG, PRESS_COMMAND, START_DATE, END_DATE, SEND_MESS_RECEPTION_TYPE, SET_FILE, SET_TEXT_DESC, SET_TYPE_123, SET_QUESTION_BACK, SET_QUESTION_TEXT,
    SET_TEXT_CAUSE_TO_RENEWAL, SET_RENEWAL_DEADLINE, CHOOSE_REQUEST_RESPONSIBLE, REQUEST_RESPONSIBLE_HANDLER, ADD_DIRECTOR, CHOOSE_REQUEST_FOR_APPROVAL, CHOOSE_REQUEST_RESPONSIBLE_NACH, REQUESTS_FOR_APPROVAL, CONFIRM, SET_NAME_FOR_REQUEST_APPEAL_TASK, SET_EMAIL, SET_FAQ_ANSWER_RUS, SET_FAQ_ANSWER_KAZ, CHOOSE_FAST_ANSWER, SET_SN, SET_OKRUG,
    CHOOSE_MENU_SECTION, MENU, ORDERING, DELIVERY_METHOD, CHANGE_NAME, CONFIRM_NAME, CONFIRM_PHONE, CHANGE_PHONE, FINISH_ORDER, GET_LOCATION, PAYMENT_METHOD, GET_MONEY_SUM, EXACT_MONEY_SUM, CHOOSE_ORDER, GET_ORDER, GET_SUGGESTION, ATTACH_MEDIA, GET_COMPLAINT, ABOUT_US, CHOOSE_STAFF, ALL_STAFF, COURIER, OPERATOR, CHOOSE_SUB_CATEGORY,
    CHOOSE_OPTION, CHOOSE_FOOD, SHOW_FOOD, EDIT_NAME, EDIT_DESCRIPTION, EDIT_PRICE, DELETE, EDIT_FOOD, EDIT_CONFIRM, EDIT_PHOTO, GET_NAME, GET_DESCRIPTION, GET_PRICE, GET_PHOTO, FINISH, GET_NAME_RU, GET_NAME_KZ, GET_DESCRIPTION_RU, GET_DESCRIPTION_KZ, SHOW_CATEGORY, EDIT_NAME_KZ, EDIT_NAME_RU, EDIT_DESCRIPTION_KZ, EDIT_DESCRIPTION_RU,
    CHOOSE_CATEGORY, CHOOSE_COURIER, CHOOSE_GENDER, SELECT_STATUS, CONFIRM_STATUS, GRADING, CHOOSE_EMPLOYEE, EDIT_EMPLOYEE, SHOW_EMPLOYEE, GET_EMPLOYEE, CHOOSE_SUGGESTION, SHOW_SUGGESTION, SET_SPECIAL_OFFER, CONFIRM_SPECIAL_OFFER, SEARCH_BUTTON, SET_CASHBACK, GET_CASHBACK, CHOOSE_BRANCH, SHOW_BRANCH, EDIT_BRANCH,
    IS_INLINE, LEAVE_COMMENT, GET_PHONE, SHOW_KASPI, EDIT_PHONE, EDIT_KASPI


}
